### ISSUE TITLE
Incompatibility Between substreams-near v0.10.0 and substreams v0.6

### ISSUE THREAD

**Issue by zolting** [streamingfast/substreams-near#2]
The substreams-near crate version 0.10.0 is currently incompatible with Substreams v0.6

This seems to be caused by [substreams-near v0.10.0](https://crates.io/crates/substreams-near/0.10.0) depending on an [outdated version (v0.10.1) of the substreams-near-core crate](https://crates.io/crates/substreams-near-core/versions). This version of substreams-near-core is over a year old and does not align with the more recent v0.10.0 version

**Comment by maoueh** [comment]
Should be fixed now, can you re-test and report?

**Comment by zolting** [comment]
Yep, works just fine now. Thank you!
